version: '3'

services:
  python:
    image: python:3.11
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    command: >
      sh -c "pip install -r requirements.txt && cd temp && python manage.py runserver 0.0.0.0:8000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

volumes:
  mongodb_data:
