version: '3'

services:
  python:
    image: python:3.11
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code
    command: tail -f /dev/null
    
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
